//! Generates `docs/PROTOCOL-VECTORS.md` from one example of every binary message
//! and asserts the two worked examples from AGENTS.md section 13.1.

use fighter_protocol::feed::{FeedFrame, MatchResult, MatchStart};
use fighter_protocol::udp::{BindRole, UdpDatagram};
use std::net::{Ipv4Addr, SocketAddrV4};

fn hex_spaced(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn udp_examples() -> Vec<(&'static str, Vec<u8>)> {
    vec![
        (
            "BIND (host, 1 local candidate 192.168.0.5:7777, token 00..0f)",
            UdpDatagram::Bind {
                session_token: std::array::from_fn(|i| i as u8),
                role: BindRole::Host,
                candidates: vec![SocketAddrV4::new(Ipv4Addr::new(192, 168, 0, 5), 7777)],
            }
            .encode(),
        ),
        (
            "BOUND (observed 203.0.113.9:40000)",
            UdpDatagram::Bound {
                observed: SocketAddrV4::new(Ipv4Addr::new(203, 0, 113, 9), 40000),
            }
            .encode(),
        ),
        (
            "RELAY (key 0102030405060708, payload 3 bytes)",
            UdpDatagram::Relay {
                relay_key: [1, 2, 3, 4, 5, 6, 7, 8],
                payload: vec![0xaa, 0xbb, 0xcc],
            }
            .encode(),
        ),
        (
            "RELAYED (payload 3 bytes)",
            UdpDatagram::Relayed {
                payload: vec![0xaa, 0xbb, 0xcc],
            }
            .encode(),
        ),
        (
            "PING (nonce 0x01020304, time 1000)",
            UdpDatagram::Ping {
                nonce: 0x0102_0304,
                client_time_ms: 1000,
            }
            .encode(),
        ),
        (
            "PONG (nonce 0x01020304, time 1000)",
            UdpDatagram::Pong {
                nonce: 0x0102_0304,
                client_time_ms: 1000,
            }
            .encode(),
        ),
    ]
}

fn feed_examples() -> Vec<(&'static str, Vec<u8>)> {
    vec![
        (
            "MATCH_START (match 7, stage 4 beach, jin vs valka)",
            FeedFrame::MatchStart(MatchStart {
                feed_version: 1,
                match_id: 7,
                stage_index: 4,
                p1_fighter_index: 4,
                p2_fighter_index: 3,
                game_version: "0.4.1".into(),
                stage_id: "beach".into(),
                p1_fighter_id: "jin".into(),
                p2_fighter_id: "valka".into(),
                p1_name: "Lino".into(),
                p2_name: "Lufi".into(),
            })
            .encode()
            .unwrap(),
        ),
        (
            "INPUTS (match 7, first tick 0, P1 right+LP, P2 neutral, two ticks)",
            FeedFrame::Inputs {
                match_id: 7,
                first_tick: 0,
                inputs: vec![(0x0016, 0x0005), (0x0016, 0x0005)],
            }
            .encode()
            .unwrap(),
        ),
        (
            "CHECKSUM (match 7, tick 120)",
            FeedFrame::Checksum {
                match_id: 7,
                tick: 120,
                checksum: 0xdead_beef,
            }
            .encode()
            .unwrap(),
        ),
        (
            "MATCH_END (match 7, final tick 5000, P1 won 2-1)",
            FeedFrame::MatchEnd {
                match_id: 7,
                final_tick: 5000,
                result: MatchResult::P1Won,
                p1_wins: 2,
                p2_wins: 1,
            }
            .encode()
            .unwrap(),
        ),
        (
            "FEED_RESET (match 7)",
            FeedFrame::FeedReset { match_id: 7 }.encode().unwrap(),
        ),
    ]
}

#[test]
fn spec_vectors_match_exactly() {
    let ping = UdpDatagram::Ping {
        nonce: 0x0102_0304,
        client_time_ms: 1000,
    };
    assert_eq!(hex_spaced(&ping.encode()), "f4 04 03 02 01 e8 03 00 00");

    let inputs = FeedFrame::Inputs {
        match_id: 7,
        first_tick: 0,
        inputs: vec![(0x0016, 0x0005), (0x0016, 0x0005)],
    };
    assert_eq!(
        hex_spaced(&inputs.encode().unwrap()),
        "02 07 00 00 00 00 00 00 00 02 00 16 00 05 00 16 00 05 00"
    );
}

#[test]
fn writes_protocol_vectors_doc() {
    let mut out = String::new();
    out.push_str("# Protocol vectors\n\n");
    out.push_str(
        "Generated by `crates/protocol/tests/vectors.rs`. Do not edit by hand; run\n\
         `cargo test -p fighter-protocol` to regenerate. All integers are little-endian.\n\n",
    );

    out.push_str("## UDP datagrams (section 7.1)\n\n");
    for (label, bytes) in udp_examples() {
        out.push_str(&format!("- **{label}** ({n} bytes)\n\n", n = bytes.len()));
        out.push_str(&format!("  ```\n  {}\n  ```\n\n", hex_spaced(&bytes)));
    }

    out.push_str("## Spectator feed frames (section 8.1)\n\n");
    for (label, bytes) in feed_examples() {
        out.push_str(&format!("- **{label}** ({n} bytes)\n\n", n = bytes.len()));
        out.push_str(&format!("  ```\n  {}\n  ```\n\n", hex_spaced(&bytes)));
    }

    out.push_str(
        "## Round-trip\n\nEvery vector above decodes back to the message that produced it; ",
    );
    out.push_str("this is checked by the round-trip property tests.\n");

    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("docs")
        .join("PROTOCOL-VECTORS.md");
    std::fs::write(&path, out).expect("write PROTOCOL-VECTORS.md");
}
